#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "terraform fmt -check -recursive" > .husky/pre-commit
echo "terraform validate" >> .husky/pre-commit
echo "terraform validate" >> .husky/pre-commit